### ISSUE TITLE
ctf-whale配置问题

### ISSUE THREAD

**Issue by pperk** [Err0rCM/CTFd_with_CTFd-whale#1]
师傅，这里你用的ctf-whale和文章里的不一样，能不能也讲下参数是怎么配的（指的是平台起来后管理页面设置题目和frp ip那里）。

**Comment by Err0rCM** [comment]
你好！感谢阅读，新的插件配置已更改，总体还是和以前差不多的，如有疑问可以再提出。
![image](https://user-images.githubusercontent.com/68117733/115982813-6b7bfb00-a5d0-11eb-9388-2e9947cf6dfd.png)
![image](https://user-images.githubusercontent.com/68117733/115982841-98301280-a5d0-11eb-9517-8bf9db114c9f.png)
