### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Augenstern-cmd** [Err0rCM/CTFd_with_CTFd-whale#6]
整合那个 启动之后出现下面的提示，是什么原因啊
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.cache: 'cpus'
Unsupported config option for services.ctfd: 'cpus'
Unsupported config option for services.db: 'cpus'
Unsupported config option for services.frpc: 'cpus'
Unsupported config option for services.nginx: 'cpus'

**Comment by Err0rCM** [comment]
docker-compose版本过低或docker-compose.yml配置错误，请检查
